// <auto-generated />
namespace mr_bahaa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class studentip : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(studentip));
        
        string IMigrationMetadata.Id
        {
            get { return "202209132227138_studentip"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
